FROM openjdk:21
EXPOSE 8080
ADD ./target/doctor-reception-application-0.0.1-SNAPSHOT.jar doctor-reception
ENTRYPOINT ["java","-jar","/doctor-reception.jar"]
#ENV Asia/tehran
LABEL maintainer="sajjadtavakoli76@gmail.com"